---
config:
  layout: elk
---
erDiagram
	direction TB
	UTENTE {
		int id PK ""  
		string email UK ""  
		string nome  ""  
		string cognome  ""  
		string password  ""  
		string ruolo  ""  
		int eta  ""  
		float altezza  ""  
		float peso  ""  
		string condizione  ""  
		int id_P1 FK ""  
		string Professionista_1  ""  
		int id_P2 FK ""  
		string Professionista_2  ""  
	}

	PROFESSIONISTA {
		int id PK ""  
		string email UK ""  
		string nome  ""  
		string cognome  ""  
		string password  ""  
		string ruolo  ""  
	}

	RUOLO {
		string id PK ""  
		string nome  ""  
	}

	ALBO {
		int id_professionista PK ""  
		string id_ruolo PK ""  
		string tipo  ""  
	}

	CALENDARIO {
		date data PK ""  
		int id_utente PK ""  
		int id_pasto FK ""  
		int id_workout FK ""  
		string tipo  ""  
	}

	PASTO {
		int id PK ""  
		int id_utente FK ""  
		string nome  ""  
		date data  ""  
		string tipo  ""  
		float calorie_totali  ""  
		date data_creazione  ""  
	}

	ALLENAMENTO {
		int id PK ""  
		int id_utente FK ""  
		string nome  ""  
		date data  ""  
		int durata_minuti  ""  
		date data_creazione  ""  
	}

	VALUTAZIONE {
		int id PK ""  
		int id_pasto FK ""  
		int id_allenamento FK ""  
		int id_professionista FK ""  
		int voto  ""  
		string commento  ""  
		date data_valutazione  ""  
	}

	DETTAGLI_PASTO {
		int id_pasto FK ""  
		int id_alimento FK ""  
		float quantita_grammi  ""  
		float kcal_calcolate  ""  
	}

	DETTAGLI_ALLENAMENTO {
		int id_allenamento FK ""  
		int id_esercizio FK ""  
		sting ripetizioni  ""  
		int pesi_kg  ""  
		int riposo_minuti  ""  
	}

	ALIMENTO {
		int id PK ""  
		string nome  ""  
		float kcal_per_100g  ""  
		float proteine_g  ""  
		float carboidrati_g  ""  
		float zuccheri_g  ""  
		float grassi_g  ""  
		string categoria  ""  
	}

	ESERCIZIO {
		int id PK ""  
		string nome  ""  
		string gruppo_muscolare  ""  
	}

	PROFESSIONSTA_ALIMENTARE {

	}

	PROFESSIONISTA_ALLENAMENTI {

	}

	BACHECA_CONDIVISA {

	}

	UTENTE||--o{PASTO:"crea/modifica"
	UTENTE}o--o{PASTO:"visualizza/condivide"
	UTENTE||--o{ALLENAMENTO:"crea/modifica"
	UTENTE||--o{ALLENAMENTO:"visualizza/condivide"
	UTENTE||--o{CALENDARIO:"crea/modifica"
	UTENTE}o--o{CALENDARIO:"visualizza"
	UTENTE}o--o{PROFESSIONISTA:"è associato a"
	PROFESSIONSTA_ALIMENTARE}o--o{VALUTAZIONE:"assegna"
	PROFESSIONSTA_ALIMENTARE||--||PROFESSIONISTA:"è istanza di"
	PROFESSIONISTA_ALLENAMENTI||--||PROFESSIONISTA:"è istanza di"
	PASTO||--o{VALUTAZIONE:"riceve"
	PASTO||--||DETTAGLI_PASTO:"include"
	ALIMENTO}o--o{DETTAGLI_PASTO:"è presente in"
	CALENDARIO||--o{PASTO:"Contiene"
	PROFESSIONISTA}o--|{RUOLO:"sceglie"
	PROFESSIONSTA_ALIMENTARE||--o{PASTO:"crea"
	PROFESSIONSTA_ALIMENTARE}o--o{PASTO:"visualizza/modifica"
	PROFESSIONISTA_ALLENAMENTI||--o{ALLENAMENTO:"crea"
	PROFESSIONISTA_ALLENAMENTI}o--o{ALLENAMENTO:"visualizza/modifica"
	PROFESSIONISTA}o--||ALBO:"iscrito a"
	ALLENAMENTO||--o{VALUTAZIONE:"riceve"
	ALLENAMENTO||--||DETTAGLI_ALLENAMENTO:"include"
	ESERCIZIO}o--o{DETTAGLI_ALLENAMENTO:"è presente in"
	BACHECA_CONDIVISA||--o{PASTO:"contiene"
	BACHECA_CONDIVISA||--o{ALLENAMENTO:"contiene"